---
nodes:
  hosts:
    balboa:
      ansible_host: 192.168.56.201
    creed:
      ansible_host: 192.168.56.202
    clang:
      ansible_host: 192.168.56.203
    drago:
      ansible_host: 192.168.56.204
  vars:
    ansible_user: vagrant
    ansible_become: true