---
nodes:
  hosts:
    leonardo:
      ansible_host: 192.168.56.11
    raphael:
      ansible_host: 192.168.56.12
    donatello:
      ansible_host: 192.168.56.13
    michelangelo:
      ansible_host: 192.168.56.14
  vars:
    ansible_user: vagrant
    ansible_become: true